### ISSUE TITLE
Wrong error message when the driver can't get a session on a specific time

### ISSUE THREAD

**Issue by othonrsanchez** [awslabs/amazon-qldb-driver-java#13]
Problem:

The PooledQldbSession throws an exception when it can't get one in the specified `poolTimeout`. [See code](https://github.com/awslabs/amazon-qldb-driver-java/blob/master/src/main/java/software/amazon/qldb/PooledQldbDriver.java#L337). When that happens, the error message used on the exception comes from the [errors.properties](https://github.com/awslabs/amazon-qldb-driver-java/blob/master/src/main/resources/errors.properties#L9). 

The exception message looks like this: `software.amazon.qldb.exceptions.QldbClientException: No available sessions returned to the session pool for use after 30000 seconds. Close some active sessions and try again.`

The message is inaccurate as the driver didn't wait 30k seconds but 30 seconds.

Steps to reproduce the issue:
1. Create a driver with a pool limit of 1 second and a pool limit of 1.
1. Using 2 threads, get a session and sleep the thread for over a second inside the `QldbSession.execute` method.
1. The second thread should fail to get a session and should throw an error message like: `software.amazon.qldb.exceptions.QldbClientException: No available sessions returned to the session pool for use after 1000 seconds. Close some active sessions and try again.``

**Comment by aurghob33** [comment]
This is was resolved as part of 1.x version of the driver.

**Comment by aurghob33** [comment]
Not present in v2 of the driver. Closing.
